# Generated by Django 2.1.12 on 2019-10-05 14:07

import django.db.models.deletion
from django.db import migrations, models

import cms.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [("cms", "0022_auto_20180620_1551")]

    operations = [
        migrations.CreateModel(
            name="Society",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "content",
                    cms.models.fields.PlaceholderField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        slotname="content",
                        to="cms.Placeholder",
                    ),
                ),
            ],
            options={"verbose_name": "society", "verbose_name_plural": "societies"},
        ),
        migrations.CreateModel(
            name="SocietyPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="societies_societyplugin",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                (
                    "page_link",
                    cms.models.fields.PageField(
                        blank=True,
                        help_text="Page to link to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms.Page",
                        verbose_name="page",
                    ),
                ),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="societies.Society",
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("cms.cmsplugin",),
        ),
    ]
