# Generated by Django 2.1.12 on 2019-10-05 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("societies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="society",
            name="members",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        )
    ]
