# Generated by Django 2.1.12 on 2019-10-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URLConfMenuEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(max_length=50, verbose_name="app name")),
                ("name", models.CharField(max_length=50, verbose_name="url name")),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="display name"),
                ),
                (
                    "namespace",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="url namespace"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "urlconf menu entry",
                "verbose_name_plural": "urlconf menu entries",
            },
        )
    ]
