# Generated by Django 4.2.9 on 2025-01-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="URLConfMenuEntry",
        ),
    ]
