language: python

python: "3.6"

env:
  global:
    - DJANGO_SETTINGS_MODULE=langerak_gkv.conf.travis
    - SECRET_KEY=travis

jobs:
  include:

    - stage: Tests
      name: Django tests
      cache:
        directories:
          - $HOME/.pip-cache
      services:
        - elasticsearch
        - postgresql
      install:
        - pip install --upgrade setuptools pip
        - pip install -r requirements/test.txt --cache-dir $HOME/.pip-cache
        - npm ci
      before_script:
        - mkdir log
        - src/manage.py collectstatic --noinput --link
      script:
        - coverage run src/manage.py test src -v 2
      after_success:
        - codecov

    - name: Isort
      install:
        - pip install isort
      script: isort --recursive --check-only --diff .

    - name: Black
      install:
        - pip install black
      script: black --check src


    - stage: Docker build
      name: Build image
      services:
        - docker
      script:
        - bin/build_image.sh
      deploy:
        - provider: script
          script: PUSH=yes bin/build_image.sh latest
          on:
            branch: develop
        - provider: script
          script: PUSH=yes bin/build_image.sh $TRAVIS_TAG
          on:
            tags: true
