# Generated by Django 4.2.25 on 2026-01-24 13:19

from django.db import migrations


def remove_static_placeholders(apps, _):
    StaticPlaceholder = apps.get_model("cms", "StaticPlaceholder")
    StaticPlaceholder.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210131_1532"),
        ("cms", "0022_auto_20180620_1551"),
    ]

    operations = [
        migrations.RunPython(remove_static_placeholders, migrations.RunPython.noop),
    ]
