# Generated by Django 4.2.25 on 2026-01-24 14:29

from django.db import migrations


def delete_page_drafts(apps, _):
    Page = apps.get_model("cms", "Page")
    PageUrl = apps.get_model("cms", "PageUrl")
    PageContent = apps.get_model("cms", "PageContent")

    paths_seen: set[str] = set()
    page_urls = PageUrl.objects.order_by("path", "page__changed_date")

    to_delete = []
    for url in page_urls:
        if url.path in paths_seen:
            to_delete.append(url.page)
            continue
        paths_seen.add(url.path)

    # move metadata over
    for page in to_delete:
        page_content = PageContent.objects.get(page=page)

        other_page = page.node.cms_pages.exclude(pk=page.pk).get()
        other_page_content = PageContent.objects.get(page=other_page)

        Page.objects.filter(pk=other_page.pk).update(
            created_by=page.created_by,
            changed_by=page.changed_by,
            creation_date=page.creation_date,
            changed_date=page.changed_date,
        )
        PageContent.objects.filter(pk=other_page_content.pk).update(
            created_by=page_content.created_by,
            changed_by=page_content.changed_by,
            changed_date=page_content.changed_date,
        )

    Page.objects.filter(pk__in=(x.pk for x in to_delete)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_wipe_static_placeholders"),
        ("cms", "0036_auto_20240311_1028"),
    ]

    operations = [
        migrations.RunPython(delete_page_drafts, migrations.RunPython.noop),
    ]
