# Generated by Django 2.1.15 on 2020-02-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_auto_20191201_1714"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PrayerOnDemand",
        ),
    ]
