# Generated by Django 2.1.12 on 2019-11-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20191109_1733")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="username"
            ),
        ),
    ]
