# Generated by Django 2.2.17 on 2021-02-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_auto_20191109_1735"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(_negated=True, email=""),
                fields=("email",),
                name="unique_email",
            ),
        ),
    ]
