# Generated by Django 2.2.24 on 2021-08-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20210209_2022"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="member_type",
        ),
    ]
