---

- name: Install supervisord
  package: name=supervisor state=present
  remote_user: root

- name: Install the Django config
  template: src=django.conf.j2 dest="/etc/supervisor/conf.d/uwsgi-{{ konkerk }}-{{ env }}.conf"
  remote_user: root
  notify:
    - restart uwsgi

- name: Enable the supervisor program
  supervisorctl: name="uwsgi-{{ konkerk }}-{{ env }}" state=present
  remote_user: root

- name: Start the supervisor program
  supervisorctl: name="uwsgi-{{ konkerk }}-{{ env }}" state=started
  remote_user: root
