---

# Run the commands/cronjobs as root user, using the existing web container

- name: Cron - send e-mails
  cron:
    name: "[{{ user }} - {{ env }}] send e-mails"
    minute: "*/2"
    job: >
      docker exec {{ user }}-{{ env }}-web python src/manage.py send_mail
  remote_user: root

- name: Cron - retry deferred emails
  cron:
    name: "[{{ user }} - {{ env }}] retry deferred e-mails"
    minute: 0,20,40
    job: >
      docker exec {{ user }}-{{ env }}-web python src/manage.py retry_deferred
  remote_user: root

- name: Cron - update elastic search index
  cron:
    name: "[{{ user }} - {{ env }}] update elastic search index"
    minute: 10,30,50
    job: >
      docker exec {{ user }}-{{ env }}-web python src/manage.py update_index
  remote_user: root
