---
# Install the frontend dependencies

- name: Remove global npm programs
  npm:
    name: "{{ item }}"
    global: yes
    state: absent
  with_items:
    - jspm
    - gulp
  remote_user: root

- name: Install project dependencies with Node
  npm:
    path: "{{ project_home }}"
    production: no  # we need the build tooling, for now

- name: Build the frontend
  command: npm run build
  args:
    chdir: "{{ project_home }}"
