---
# Install the frontend dependencies

- name: Install project dependencies with Node
  npm:
    path: "{{ project_home }}"
    production: no  # we need the build tooling, for now

# - name: Build the frontend
#   command: npm run build
#   args:
#     chdir: "{{ project_home }}"
