---
# Main tasks file to distribute the subtasks

- name: Ensure project_home dir exists
  file:
    path: "{{ project_home }}"
    state: directory
    mode: 0750
    owner: "{{ user }}"
    group: "{{ user }}"

- import_tasks: secrets.yml
- import_tasks: media.yml
- import_tasks: containers.yml
# Should spin up container
# - import_tasks: cronjobs.yml
