---
# Main tasks file to distribute the subtasks

- include: install_os_packages.yml
- include: checkout_code.yml
- include: dependencies.yml
- include: db.yml
- include: secrets.yml
- include: migrate.yml
- include: frontend.yml
- include: media.yml
- include: collectstatic.yml
- include: cronjobs.yml
