---

# Install Elastic Search

- name: Add apt-key for Elastic Search
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    id: "{{ es_key_fingerprint }}"
  remote_user: root

- name: Add Elastic Search sources
  apt_repository:
    repo: "deb https://packages.elastic.co/elasticsearch/{{ es_version }}/debian stable main"
    state: present
    filename: "elasticsearch-{{ es_version }}"
  remote_user: root

- name: Install Elastic Search
  package:
    name: elasticsearch
    state: present
    update_cache: yes
  remote_user: root
