---

# Install Elastic Search

- name: Add apt-key for Elastic Search
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    id: "{{ es_key_fingerprint }}"

- name: Add Elastic Search sources
  apt_repository:
    repo: "deb https://packages.elastic.co/elasticsearch/{{ es_version }}/debian stable main"
    state: present
    filename: "elasticsearch-{{ es_version }}"

- name: Install Elastic Search
  package:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Ensure Elastic Search is running
  service:
    name: elasticsearch
    state: started
    enabled: yes
