---

- name: Deploy with Docker
  hosts: web
  remote_user: root

  vars:
    image: "regexit/kerkwebsite:{{ image_tag|default('latest') }}"
    nginx_file_dirs:
      - "{{ storage_path }}"

  roles:
    - role: users
    - role: geerlingguy.docker
    - role: database
    - role: django
    - role: nginx
