---

- name: Deploy with Docker
  hosts: all
  remote_user: root

  vars:
    image: regexit/kerkwebsite:latest
    nginx_file_dirs:
      - "{{ storage_path }}"

  roles:
    - role: users
    - role: geerlingguy.docker
    - role: database
    - role: django
    - role: nginx
