---
# Deploys the application code to the server
- name: Update the application to the latest version
  hosts: web
  vars:
    deploy_env: "{{ target|default('staging') }}"
    release: "{{ release_tag|default('master') }}"
    repository: https://github.com/sergei-maertens/langerak-gkv.git
    settings_module: conf.settings.{{ deploy_env }}
    project_home: "{{ ansible_env.HOME }}/django/{{ deploy_env }}"
  remote_user: lang
  roles:
    - django
