---
# Deploys the application code to the server
- name: Update the application to the latest version
  hosts: production
  vars:
    deploy_env: "{{ target|default('staging') }}"
    release: "{{ release_tag|default('master') }}"
    repository: https://github.com/sergei-maertens/langerak-gkv.git
    settings_module: langerak_gkv.conf.{{ deploy_env }}
    project_home: "{{ ansible_env.HOME }}/django/{{ deploy_env }}"
    venv: "{{ project_home }}/env"
    ports: {staging: 8011, production: 8010}
  remote_user: konkerk
  roles:
    - git
    - postgres
    - supervisor
    - nginx
    - django
