# Generated by Django 2.1.12 on 2019-10-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Church",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
            ],
        ),
        migrations.CreateModel(
            name="Liturgy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                ("preacher", models.CharField(max_length=100, verbose_name="preacher")),
                (
                    "preach_author",
                    models.CharField(max_length=100, verbose_name="preach author"),
                ),
                (
                    "main_section",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="main section"
                    ),
                ),
                (
                    "main_chapter",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="main chapter"
                    ),
                ),
                (
                    "main_verse",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="main verse"
                    ),
                ),
                (
                    "service_theme",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="service theme"
                    ),
                ),
                ("liturgy", models.TextField(verbose_name="liturgy")),
                (
                    "audiofile",
                    models.FileField(
                        blank=True,
                        upload_to="liturgies/audio",
                        verbose_name="audiofile",
                    ),
                ),
                (
                    "beamist",
                    models.CharField(blank=True, max_length=50, verbose_name="beamist"),
                ),
                (
                    "organist",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="organist"
                    ),
                ),
                (
                    "collection_goal1",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="collection goal 1"
                    ),
                ),
                (
                    "collection_goal2",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="collection goal 2"
                    ),
                ),
                (
                    "collection_goal3",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="collection goal 3"
                    ),
                ),
                (
                    "extra_information",
                    models.TextField(blank=True, verbose_name="extra information"),
                ),
                (
                    "internal_remarks",
                    models.TextField(blank=True, verbose_name="remarks (internal)"),
                ),
            ],
            options={
                "verbose_name": "liturgy",
                "verbose_name_plural": "liturgies",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MailRecipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "function",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0preacher", "predikant (predikant@langerak.gkv.nl)"),
                            ("koster", "koster (koster@langerak.gkv.nl)"),
                            ("2beamist", "beamist (beamist@langerak.gkv.nl)"),
                            ("1organist", "organist (organist@langerak.gkv.nl)"),
                            (
                                "biblegroup",
                                "bible group (bijbelleesgroep@langerak.gkv.nl)",
                            ),
                            (
                                "preach_creation",
                                "preach creation (preekvoorziening@langerak.gkv.nl)",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "liturgy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liturgies.Liturgy",
                        verbose_name="liturgy",
                    ),
                ),
            ],
            options={"ordering": ["function"]},
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="service name")),
                ("time", models.TimeField(verbose_name="service time")),
            ],
        ),
    ]
