# Generated by Django 2.1.13 on 2019-12-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("liturgies", "0002_auto_20191005_1607")]

    operations = [
        migrations.AlterField(
            model_name="liturgy",
            name="liturgy",
            field=models.TextField(blank=True, verbose_name="liturgy"),
        ),
        migrations.AlterField(
            model_name="liturgy",
            name="preach_author",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="preach author"
            ),
        ),
        migrations.AlterField(
            model_name="liturgy",
            name="preacher",
            field=models.CharField(blank=True, max_length=100, verbose_name="preacher"),
        ),
    ]
