# Generated by Django 2.1.13 on 2020-01-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("liturgies", "0003_auto_20191230_1847")]

    operations = [
        migrations.AddField(
            model_name="liturgy",
            name="download",
            field=models.FileField(
                blank=True,
                help_text="Downloadable attachment, for example a Word file.",
                upload_to="liturgies/downloads",
                verbose_name="download",
            ),
        )
    ]
