# Generated by Django 2.1.13 on 2020-01-20 08:13

from django.db import migrations
from django.template.defaultfilters import linebreaksbr


def convert_to_html(apps, _):
    Liturgy = apps.get_model("liturgies.Liturgy")
    for liturgy in Liturgy.objects.all():
        liturgy.liturgy = linebreaksbr(liturgy.liturgy)
        liturgy.save()


class Migration(migrations.Migration):

    dependencies = [("liturgies", "0005_auto_20200120_0910")]

    operations = [migrations.RunPython(convert_to_html, migrations.RunPython.noop)]
