# Generated by Django 2.2.17 on 2021-01-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("liturgies", "0007_auto_20210131_1519"),
        ("liturgies", "0008_auto_20210131_1520"),
    ]

    dependencies = [
        ("liturgies", "0006_auto_20200120_0913"),
    ]

    operations = [
        migrations.RenameField(
            model_name="liturgy",
            old_name="main_section",
            new_name="bible_readings",
        ),
        migrations.AlterField(
            model_name="liturgy",
            name="audiofile",
            field=models.FileField(
                blank=True,
                editable=False,
                help_text="Audio downloads are no longer available as of Jan. 31st - this field has been disabled.",
                upload_to="liturgies/audio",
                verbose_name="audiofile",
            ),
        ),
        migrations.RemoveField(
            model_name="liturgy",
            name="main_chapter",
        ),
        migrations.RemoveField(
            model_name="liturgy",
            name="main_verse",
        ),
        migrations.AlterField(
            model_name="liturgy",
            name="bible_readings",
            field=models.TextField(blank=True, verbose_name="Bible readings"),
        ),
    ]
