# Generated by Django 4.2.9 on 2025-01-19 14:04

from django.db import migrations, models

import langerak_gkv.liturgies.models


class Migration(migrations.Migration):
    dependencies = [
        ("liturgies", "0010_auto_20210613_1737"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="church",
            options={"verbose_name": "church", "verbose_name_plural": "churches"},
        ),
        migrations.RemoveField(
            model_name="liturgy",
            name="beamist",
        ),
        migrations.RemoveField(
            model_name="liturgy",
            name="internal_remarks",
        ),
        migrations.RemoveField(
            model_name="liturgy",
            name="organist",
        ),
        migrations.RemoveField(
            model_name="liturgy",
            name="preach_author",
        ),
        migrations.AddField(
            model_name="church",
            name="auto_selected",
            field=models.BooleanField(
                default=False,
                help_text="If checked, liturgies will by default be related to this church.",
                verbose_name="automatically selected",
            ),
        ),
        migrations.AlterField(
            model_name="liturgy",
            name="other_churches",
            field=models.ManyToManyField(
                blank=True,
                default=langerak_gkv.liturgies.models.get_default_churches,
                to="liturgies.church",
                verbose_name="other churches",
            ),
        ),
    ]
