# Generated by Django 4.2.9 on 2025-01-19 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mail",
        ),
        migrations.DeleteModel(
            name="MailTemplate",
        ),
    ]
