---

- name: Create the nginx vhost
  template: src=vhost.j2
            dest=/usr/local/nginx/conf/vhost/koningskerk.nu.conf
            owner=root
            group=root
            mode=0644
  remote_user: root
