name: Code quality checks

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
    tags:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  isort:
    name: Check import sorting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: maykinmedia/setup-django-backend@v1.1
        with:
          apt-packages: 'libxml2-dev libxmlsec1-dev libxmlsec1-openssl'
          python-version: '3.9'
          setup-node: 'no'
          optimize-postgres: 'no'
      - uses: isort/isort-action@v1
        with:
          requirements-files: requirements/ci.txt
          sort-paths: "src doc"

  black:
    name: Check code formatting with black
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: maykinmedia/setup-django-backend@v1.1
        with:
          apt-packages: 'libxml2-dev libxmlsec1-dev libxmlsec1-openssl'
          python-version: '3.9'
          setup-node: 'no'
          optimize-postgres: 'no'

      - name: Run black
        run: |
          black --check src doc
