---

- name: Install caching servers
  package: name={{ item }} state=present
  with_items:
    - redis-server
    - memcached
    - libmemcached-tools

- name: Ensure redis only listens on localhost
  lineinfile:
    dest=/etc/redis/redis.conf
    insertafter="^# bind 192.168.1.100 10.0.0.1"
    line="bind 127.0.0.1"


