---

- name: Install the databases used
  apt:
    name:
    state: present
    - postgresql
    - postgresql-client
    - python3-dev
    - libpq-dev
    - python-psycopg2
    force: yes

# Set up PostgreSQL properly

- name: Install correct pg_hba.conf rules for postgres user
  lineinfile:
    dest: /etc/postgresql/9.4/main/pg_hba.conf
    regexp: '^local   all             (all|postgres)                                \s*(peer|ident)'
    line: 'local   all             postgres                                ident'
  notify:
    - restart postgres

- name: Enforce password auth for local postgres connections
  lineinfile:
    dest: /etc/postgresql/9.4/main/pg_hba.conf
    insertafter: 'local   all             postgres                                ident'
    line: 'local   all             all                                     md5'
  notify:
    - restart postgres
